language: python
python:
  - "3.7"
install:
  - pip install .
before_script:
  - pip install flake8 pytest-cov coveralls
script:
  - flake8 yall/ tests/
  - py.test --cov=yall tests/
after_success:
  -coveralls
